'''
LA MAYORIA DEL CODIGO PYTHON ES UN MODULO PARA IMPORTAR O UN SCRIPT QUE HACE ALGO.

SIN EMBARGO ALGUNAS VECES ES UTIL HACER UN ARCHIVO QUE PUEDA SER IMPORTADO COMO UN MODULO Y EJECUTADO COMO UN SCRIPT.

PARA HACER ESTO, COLOQUE EL SCRIPT DENTRO DE IF __name__ == '__main__':

ESTO ASEGURARA QUE NO SERA EJECUTADO SI EL ARCHIVO ES IMPORTADO.

CUANDO EL INTERPRETADOR DE PYTHON LEE UN ARCHIVO FUENTE, EJECUTA EL CODIGO ENTERO QUE ENCUENTRE DENTRO DEL ARCHIVO. ANTES DE EJECUTAR EL CODIGO, DEFINE UNAS VARIABLES
ESPECIALES.

POR EJEMPLO, SI EL INTERPRETADOR PYTHON EJECUTA ESE MODULO (EL ARCHIVO FUENTE) COMO EL PROGRAMA PRINCIPAL, ESTABLECE LA VARIABLE ESPECIAL __name__ PARA TENER UN VALOR
"__main__". SI ESTE ARCHIVO ES IMPORTADO DESDE OTRO MODULO, __name__ SERA ESTABLECIDO EN EL NOMBRE DEL MODULO.
'''

def funcion():
    print("esto es una funcion")

if __name__ == '__main__':
    print("esto es un script") #se genera esta cadena

'''
ENTONCES PODEMOS IMPORTAR UN ARCHIVO EN PYTHON EN OTRO SCRIPT SI LO IMPORTAMOS CON EL NOMBRE QUE FUE GUARDADO:
'''
#EJEMPLO:
import ciclo_de_vida_de_un_objeto as cyc #esta es una libreria de ciclos



