'''
EL TERMINO EMPAQUETAMIENTO SE REFIERE A PONER MODULOS QUE HAS ESCRITO EN UN FORATO ESTANDAR, PARA QUE ASI OTROS PROGRAMADORES PUEDAN INSTALARLO E UTILIZARLO CON
FACILIDAD.

ESTO INVOLUCRA EL USO DE LOS MODULOS setuptools Y distutils.

EL PRIMER PASO EN EL EMPAQUETAMIENTO ES ORGANIZAR LOS ARCHIVOS EXISTENTES. UBIQUE TODOS LOS AQCHIVOS QUE QUIERES EN UNA BIBLIOTECA EN EL MISMO MISMO DIRECTORIO
PRINCIPAL. ESTE DIRECTORIO TAMBIEN DEBE CONTENER UN ARCHIVO LLAMADO __init__.py, QUE PUYEDE ESTAR EN BLANCO PERO DEBE ESTAR EN EL DIRECTORIO.

ESTE DIRECTORIO VA CON OTRO DIRECTORIO QUE CONTIENE EL LEEME Y LA LICENCIA, COMO TAMBIEN UN ARCHIVO DE SUMA IMPORTANCIA LLAMADO setup.py

EL SIGUENTE PASO ES ESCRIBIR EL ARCHIVO setup.py.

ESTE CONTIUENE LA INFO NECESARIA PARA ENSAMBLAR EWL PAQUETE PARA ASI SUBIRLO A PyPI E INSTALARLO CON pip (NOMBRE,VERISON,ETC)
'''
#EJEMPLO DE UNA RCHIVO SETUP.PY

