'''
all Y any SON UTILIZADO CON FRECUENCIA COMO SENTENCIAS CONDICIONEALES. ESTOS TOMAN UNA LISTA COMO ARGUMENTO Y DEVUELVEN True SI TODOS O ALGUNOS RESPECTIVAMENTE , DE SUS ARGUMENTOS SON EVALUADOS
COMO TRUE (O DE LO CONTRARIO FALSE).

LA FUNCION enumerate PUEDE UTILIZARSE PARA ITERAR A TRAVES DE LOS VALORES DE INDICES DE UNA LISTA, SIMULTANEAMENTE.
'''

#Ejemplo:

nums = [55,44,33,22,11]

if all([i>5 for i in nums]):
    print("todos son mas grades que cinco")

if any([i%2 ==0 for i in nums]):
    print("al menos uno es par")
#DEVUELVE UNA LISTA DE CADA ELEMENTO DE LA LISTA CON SU VALOR CORRESPONDIENTE:
for v in enumerate(nums):
    print(v)