'''
EL MODULO itertools ES UNA BIBLIOTECA ESTANDAR QUE CONTIENE VARIAS FUNCIONES QUE SON UTILES EN LA PROGRAMCION FUNCIONAL.
UNO DE LOS TIPOS DE FUNCION QUE PRODUCEN SON ITERADORES INFINITOS.
LA FUNCION count CUENTA INFINITAMENTE A PARTIR DE UN VALOR.
LA FUNCION cycle INTERA INFINITAMENTE A TRAVES SE UN ITERABLE (COMO UNA LISTA O CADENA).
LA FUNCION repeat REPITE UN OBEJETO, YA SEA INFINITAMENTE O UN NUMERO ESPECIFICO DE VECES
'''

from itertools import accumulate
from itertools import count

for i in count(3):
    print(i)
    if i >= 11:
        break

'''
HAY MUCHAS FUNCIONES EN ITERTOOLS QUE OPERAN SOBRE ITERABLES DE UNA MANERA SIMILAR A map O filter.

ALGUNOS EJEMPLOS:

takewhile: TOMA UN ELEMENTO DE UN ITERABLE MIENTRAS QUE UNA FUNCION PREDICADO PERMANECE VERDADERA;

chain: COMBINA VARIOS ITERABLES EN UNO SOLO MAS LARGO;

acumulate: DEVUELVE UN TOTAL ACTUALIZADO DE VALORES EJECUTADOS EN UN ITERABLE.
'''

from itertools import accumulate, takewhile

nums = list(accumulate(range(8)))
print(nums)
print(list(takewhile(lambda x: x>=6, nums)))


'''
TMABIEN HAY NUMEROSAS FUNCIONES COMBINATORIAS EN itertools, TALES COMO product y permutation.
ESTAS SON UTILIZADOS CUANDO QUIERES CUMPLIR UNA TAREA CON TODAS LAS COMBINACIONES POSIBLES DE ALGUNOS ELEMENTOS.
'''
#ESTO SE PODRIA UTILIZAR PARA HACER PERMUTACIONES DE UNA BASEDE DATOS Y ESCOJER DATOS ALEATORIOS DE ESTO:
from itertools import product, permutations

letras = ("A","B")
print(list(product(letras,range(2))))
print(permutations(letras)) #me falta averiguar como funciona esta funcion.