'''
EL OBJETO None ES UTILIZADO PARA PARA REPRECENTAR LA AUSENCIA DE UN VALOR.

ES SIMILAR A Null EN OTROS LENGUAJES DE PROGRAMACION

AL IGUAL QUE OTROS VALORES "VACIOS", TALES COMO 0,[] Y LA CADENA VACIA "", ES FALSE CUANDO ES CONVERTIDA EN UNA CADENA BOOLEANA.

CUANDO ES INGRESADA A LA CONSOLA DE PYTHON, SE VISUALIZA COMO UNA CADENA VACIA.

>>> None == None
True

>>> None 
>>> print(None)
None

EL OBJETO NONE ES DEVUELTO POR CULAQUIER FUNCION QUE NO DEVUELVA EXPLICITAMENTE ALGO MAS.
 '''

def funcion():
    print("hola")

var = funcion()
print(var)