'''
LA BIBLIOTECA ESTANADAR DE PYTHON POR SI SOLA CONTIENE UNA EXTENSICA FUNCIONALIDADD.

SIN EMBARGO ALGUNAS TAREAS REQUIEREN DEL USO DE BIBLIOTECAS DE TERCEROS ALGUNAS BIBLIOTECAS DE TERCEROS SON:

Django: ES EL MARCO DE TRABAJO DE APLICAIONES WEB MAS FRECUENTEMENTE UTILIZADO ESCRITO EN PYTHON. DJANGO POTENCIA SITIOS WEB QUE INCLUYEN INSTAGRAM Y DISQUS.
TIENE MUCHAS FUNCIONES Y CUALQUIER FUNCION QUE CAREZCA SE CUBRE CON PAQUETES DE EXTENSION.

CherryPy y Flask SON TAMBIEN MARCOS DE TRABAJO DE APLICAIONES WEB MUY CONOCIDAS.

PARA EXTRAR DATOS DE PAGINAS WEB, LA BIBLIOTECA BeatifulSoup ES MUY UTIL Y DA MEJORES RESULTADOS QUE CONSTRUIR TU PROPIO EXTRACTOR CON EXPRESIONES REGULARES.

LA BIBLIOTECA SciPy  CONTIENE NUMEROSAS EXTENSIONES A LA FUNCIONALIDAD DE NumPy.

PYTHON TAMBIEN PUEDE UTILIZARSE ÁRA EL DESARROLLO DE VIDEOJUEGOS.

USUALMENTE ES UTILIZADO COMO LENGUAJE DE SCRIPTING PARA VIDEOJUEGOS ESCRITOS EN OTROS LENGUAJES PERO PUEDE UTILIZARSE PARA HACER JUEGOS POR SI SOLOS.

PARA JUEGOS 3D PUEDE UTILIZARSE LA BIBLIOTECA Panda3D. PARA JUEGOS 2D, PUEDES UTILIZAR PYGAME.
'''