'''
SE TIENE UN INFORME SOBRE EL NUMERO DE VACUNACIONES CONTRA LA GRIPE EN UNA CLASE DE 20 PERSONAS.

TIENES LOS SIGUEINTES NUMERO:

-NUNCA: 5
-UNA VEZ: 8
-DOS VECES: 4
-TRES VECES: 3

¿CUAL ES EL NUMERO MEDIO DE VECES QUE ESAS PERSONAS HAN SIDO VACUNADAS?
'''
from statistics import mean

#UNA FORMA ES CREAR UNA LISTA DE DATOS Y UTILIZARLA PARA METERLA EN LA FUNCION mean:

vacunas_recibidas = [0,0,0,0,0,1,1,1,1,1,1,1,1,2,2,2,2,3,3,3]
media = mean(vacunas_recibidas)
print(media)

#OTRA ALTERNATIVA ES SIMPLEMENTE SUMAR EL NUMERO DE VECES QUE CADA PERSONA SE HA VACUNADO Y DIVIDIRLO ENTRE EL NUMERO DE DATOS:

nunca = 0*5
una_ves =1*8
dos_veces = 2*4
tres_veces = 3*3

print((nunca+una_ves+dos_veces+tres_veces)/20)