'''
DATA SCINCE UTILIZA DIVERSAS TECNICAS Y METODOS PARA EXTRAER CONOCIMIENTOS E IDEAS DE LOS DATOS.

PARA HABLAR SOBRE LOS BLOQUES DE CONSTRUCCION DEL ANALISIS DE DATOS ES NECESARIO TENER CONOCIMIENTOS DE CONCEPTOS DE ESTADISTICA.

COMO EJEMPLO DE CONJUNTO DE DATOS, CONCIDEREMOS LOS PRECIOS DE UN GRUPO DE PRODUCTOS:

[18,24,67,55,42,14,19,26,33]

EL CONJUNTO DE DATOS DADO INCLUYE LOS PRECIOS DE 9 PRODUCTOS.

LA mean ES EL VALOR MEDIO DEL CONJUNTO DE DATOS. PODEMOS CALCULARLO SUMANDO TODAS LAS EDADES Y DIVIDIENDO ENTRE EL NUMERO DE PERSONAS:

mean = 298/9 =33.1
'''

#MEDIA DE LOS DATOS A PARTIR DE LA LISTA:
edades = [18,24,67,55,42,14,19,26,33]

suma = sum(edades)
print(suma)
print(len(edades))

media = suma/(len(edades))
print(media)
#MEDIA DE LOS DATOS A PARTIR DE LA FUNCION mean:
from statistics import mean

from numpy import median

print(mean(edades))
'''
median: ES EL VALOR MEDIO DE UN CONJUNTO DE DATOS ORDENADOS.

PARA CALCULAR LA MEDIANA DE NUESTRO CONJUNTO DE DATOS, SE DEBEN ORDENAR PRIMERO EN ORDEN ASENDENETE.

[14,18,19,24,16,33,42,55,67]

LA MEDIANA DE LOS DATOS ES 26 YA QUE ES EL DATO QUE SE ENCUENTRA EN MEDIO DE TODOS LOS DEMAS.

SI NUESTRO CONJUNTO DE DATOS TUVIERA UN NUMERO PAR DE VALORE, TOMARIAMOS LOS DOS VALORES DEL MEDIO Y CALCULARIAMOS SU VALOR MNEDIO.
'''

#MEDIANA A PARTIR DE LA FUNCION median:

lista_precios = [14,18,19,24,26,33,42,55,67]

print(median(lista_precios))

