'''
LAS CLASES_DE_CARACTER OFRECEN UNA MANERA DE COINCIDIR CON SOLO UNO DE UN CONJUNTO ESPECIFICO DE CARACTERES.
SE CREAN COLOCANDO LOS CARACTERES QUE COINCIDEN DENTRO DE LOS CORCHETES.
'''

# import re

# pattern = r"[aeiou]"

# if re.search(pattern,"gray"):
#     print("Match 1")

# if re.search(pattern,"qwertyuiop"):
#     print("Match 2")

# if re.search(pattern,"rhythm myths"):
#     print("Match 3")

#EL CODIGO ANTERIOR HACE MATCH CON 1 Y 2 PORQUE APARECEN LETRAS DEL CONJUNTO DADO

'''
LAS CLASES DE CARACTER PUEDEN TAMBIEN COINCIDIR CON RANGOS DE CARACTERES.
ALGUNOS EJEMPLOS:
LA CLASE [a-z] COINCIDE CON CUALQUIER LETRA DEL ALFABETO EN MINUSCULAS.
LA CLASE [A-P] COINCIDE CON CUALQUIER CARACTER EN MAYUSCULAS DE G A P.
LA CLASE [0-9] COINCIDE CON CUALQUIER DIGITO.
VARIOS RANGOS PUEDEN SER INCLUIDOS EN UNA CLASE. POR EJEMPLO, [A-Za-Z] COINCIDE CON UNA LETRA EN MAYUSCULAS O MINUSCULAS.
'''

import re
pattern = r"[A-Z][A-Z][0-9]"
print(pattern)

if re.search(pattern, "LS8"):
    print("Match 1")

if re.search(pattern, "E3"):
    print("Match 2")

if re.search(pattern, "1ab"):
    print("Match 3")

'''
COLOCA UN ^ AL PRINCIPIO DE UNA CLASE DE CARACTER PARA INVERTIRLA.

ESTO HACE QUE COINCIDA CON CUALQUIER CARACTER EXCEPTO LOS QUE ESTAN INCLUIDOS.

OTROS METACARACTERES TALES COMO $ Y . NO TIENEN NINGUN SIGNIFICADO DENTRO DE LAS CLASES DE CARACTER.

EL METACARACTER ^ NO TIENE SIGNIFICADO A MENOS QUE SEA EL PRIMER METACARACTER DE UNA CLASE.
'''

# pattern = r"[^A-Z]"

# if re.search(pattern, "this is all quiet"):
#     print("Match 1")

# if re.search(pattern, "AbCdEfG123"):
#     print("Match 2")

# if re.search(pattern, "THISISALLSHOUTING"):
#     print("Match 3")

# #EL CODIGO ANTERIOR SOLO NO COINCIDE CON EL ULTIMO PORQUE TIENE PURAS MAYUSCULAS.
