'''
*,+,?,{y}.
ESTOS ESPECIFICAN EL NUMERO DE REPETICIONES.
EL METACARACTER * SIGNIFICA "CERO O MAS REPETICIONES DE LO ANTERIOR". TRATA DE COINCIDIR CON LA MAYOR CANTIDAD DE REPETICIONES POSIBLES.
LO ANTERIOR PUEDE SER UN SOLO CARACTER, UNA CLASE, O GRUPO DE CARACTERES ENTRE PARENTESIS.
+ "MATECHEA SI ENCUENTRA UNA O MAS VECES LA CADENA"
? "SIGNIFICA CERO O UNA REPRETICION"
{} LAS LLAVES PUEDEN SER UTILIZADAS PARA REPRECENTAR EL NUMERO DE REPETICIONES ENTRE DOS NUMEROS.
LA REGEX (X,Y) SIGNIFICA ENTRE X y Y REPETICIONES DE ALGO.
POR LO TANTO (0,1) ES LO MISMO QUE ?.
SI FALTA EL PRIMER NUMERO, SE AUSME QUE ES CERO. SI FALTA EL SEGUNDO NUMERO, ES TOMADO HASTA EL INFINITO.
'''
import re
#Este codigo hace match con 1 y2 ya que solo requiere que este egg y que aparezca cero o mas veces spam:
pattern = r"egg(spam)*"

if re.match(pattern, "egg"):
    print("Match 1")

if re.match(pattern, "eggspamegg"):
    print("Match 2")
if re.match(pattern, "spam"):
    print("Match 3")
