'''
NUMPY FINANCIAL ESTA CONSTRUIDO EN NUMPY, LA CUAL ES UNA PAQUETERIA USADA EN COMPÚTACION CIENTIFICA.

LA CARACTERISTICA PRINCIAL DE NUMPY SON LOS ARREGOLOS, LOS CUALES SON USADOS PARA LLEVAR A CABO CALCULOS.

UN ARREGLO TE PERMITE ALMACENAR MULTIPLES VALORES EN UNA SOLA VARIABLE

PIR EJEMPLO VAMOS A DECLARAR UNA ARREGLO DE PRECIOS:
'''

prices = [42.8,102.03,240.38,80.9] # como puedes ver el arreglo asigna multiples valores a la variable.and

'''
SE PUEDE ACCEDER A LOS VALORES DE UNA RREGLO CON EL INDICE ENTRE CORCHETES:
'''

print(prices[2])

'''
AHORA, DESPUES DE IMPORTAR LA PAQUETERIA DE NUMPY, PODEMOS APLICAR VARIAS FUNCIONES DE NUMPY EN EL ARREGLO Y OBTENER EL RESULTADO
'''

import numpy as np

#DEVUELVE EL VALOR PROMEDIO DE ARREGLO:
print(np.mean(prices))

#DEVUELVE LA DESVIACION ESTANDAR:
print(np.std(prices))

#DEVUELVE LA SUMA DE TODOS LOS VALORES:
print(np.sum(prices))

#DEVUELVE EL VALOR MAXIMO DEL ARREGLO:
print(np.max(prices))

