'''
EN ESTE PROYECTO ANALIZAREMOS EL PRECIO DEL BITCOIN, CALCULAREMOS LOS VALORES DE INVERSION Y ANALIZAREMOS LA TAZA DE RETORNO.

ESTE PROYECTO INCLUYE VARIOS PASOS, CON CADA PASO SE REQUIERE UN NUMERO DE TAREAS PARA COMPLETAR.

COMENZAREMOS CON TAREAS FACILES USANDO DATOS ESTATICOS, Y PROSEGUIREMOS CON TAREAS MAS AVANZADAS QUE USAN DATOS REALES QUE OBTENDREMOS DE LA WEB.

PARA EL FINAL DEL PROYECTO, SEREMOS CAPACES DE ENCONTRAR EL PRECIO DEL BITCOIN Y ANALIZAR Y CREAR GRAFICOS BASADOS EN SUS VALORES ANTERIORES.


EL CODIGO DADO INCLUYE UN ARREGLO QUE IDENTIFICA LOS PRECIOS DEL BITCOIN A PARTIR DEL PRIMERO DE ENERO ENTRE LOS AÑOS 2018-2021

CREA UN PROGRAMA QUE CALCULE Y DEVUELVA LA DESVIACION ESTANDAR DEL VALOR DE LOS PRECIOS
'''

import numpy as np
import numpy_financial as npf

#PRECIO DE 2018 A  2021:
bitcoin = [3869.47,7188.46,22203.31,29391.78]

print(np.std(bitcoin))

