'''
CALCULAR EL VALOR FUTURO DE UNA INVERSION

VAMOS A ASUMIR UNA INVERSION DE $1000 POR 5 AÑOS CON UNA TASA ANUAL DE RETORNO DEL 8%
NECESITAMOS CALCULAR CUAL SERA EL VALOR DE LA INVERSION DESPUES DE 5 AÑOS
'''

#En el codigo siguiente tomamos la funcion fv (future value) para calcular el valor futuro de la inversion con base en tres parametros:
'''
LA TAZA DE INTERES ESTA DADA COMO UN DECIMAL (SIENDO 1 REPRECENTACION DEL 100%) ASI ENTONCES 8% ES: 0.08

nper: ES EL NUMERO DE PERIODOS

pv: ES EL VALOR PRECENTE, EL CUAL EN NUESTRO CASO ES UNA INVERSION DE $1000, POR ESO EL SIGNO NEGATIVO

pmt: CORRESPONDE A LOS PAGOS PERIODICOS/ INVERSIONES, LOS CUALES EN NUESTRO CASO ES 0
'''
import numpy_financial as npf

res = npf.fv(rate = 0.08, nper = 5, pmt = 0, pv = -1000)
print(res)
