'''
LA FUNCION pmt() ES USADO PARA CLACULAR EL PAGO PRINCIPAL (PAGO INICIAL) DEL PRESTAMO MAS LOS INTERESES.

QUEREMOS CALCULAR CUANTO TENTEMOS QUE PAGAR MENSUALMENTE PARA PAGAR UN PRESTAMO DE 100,000 EN 5 AÑOS. EL INTERES ANUAL ES 7%, Y SE CLACULA MENSUALEMENTE.
'''

import numpy_financial as npf

# print(npf.pmt(rate = 0.07/12, nper = 5*12, pv = 100000, fv = 0))

'''
COMO NECESITAMOS CALCULAR LOS PAGOS MENSUALES, COLOCAMOS LA TAZA EN PERIODOS DE MES (0.07/12)
fv MUESTRA EL VALOR FUTURO QUE QUEREMOS LOGRAR.


NOTA QUE ADEMAS DE CALCULAR EL MONTO DE PAGO MENSUAL, LA FUNCION pmt() PUEDE USARSE PARA DEVOLVER EL DEPOSITO PERIODICO QUE DEBEMOS HACER PARA LOGRAR SATISFACER 
EL BALANCE FUTURO CON UNA TASA DE INTERES DADA.
'''

# print(npf.pmt(rate = 0.10/12, nper = 5*12, pv = 0, fv = 50000))

#EL CODIGO DADO DEVUELVE LOS DEPOSITOS MENSUALES QUE DEBEMOS HACER PARA PAGAR UN PRESTAMO DE 50,000 EN 5 AÑOS CON UNA TASA DE INTERES DE 10%

#PARA PRESTAMO BBVA:
pagos_mensuales = npf.pmt(rate = 0.4/12, nper = 2*12, pv = 5000, fv = 0)
print(pagos_mensuales)

total_pago = pagos_mensuales * 12

print(total_pago) #SALE MAS BAJO A LO QUE MARCA LA APLICACION.
