'''
SIMILARMENTE CONO MLA FUNCION fv NOS DA EL VALOR FUTURO, LA FUNCION pv() ES USADO PARA CLACULAR EL VALOR PRESENTE DE INVERSION.

POR EJEMPLO VAMOS A CALCULAR EL VALOR PRESENTE DE INVERSION QUE SE NECESITA PARA UN TOTAL DE 1000 EN 8 AÑOS, CON UNA TAZA DE RETORNO ANUAL DE 10%.
'''

import numpy_financial as npf

print(npf.pv(rate = 0.10, nper = 8, pmt = 0, fv= 1000))

import hola

