'''
REGLAS DE ORO PARA INVERSIONISTAS:

1. COMPRAR BARATO Y VENDER CARO


HISTORIA:
ANTERIORMENTE LOS BILLETES ERAN CHEQUES AL PORTADOR QUE ESTABAN VALORADOS EN ORO Y SE PODIAN CAMBIAR EN BANCOS. TODO EL DIENERO ESTABA RESPALADADO EN ORO.

-EXISTE UN MOMENTO CRITICO EN EL QUE UN BANCO COMIENZA A PRODUCIR MAS DINERO DEL QUE EXISTE EN ORO, AHI ES CUANDO SE DEVALUA UNA MONEDA DEBIDO A QUE HAY MAS MONEDAS
EN CIRCULACION DE LAS QUE SE TIENEN EN ORO.
MONOPOLIO: SITUACION DE PRIVILEGIO LEGAL EN LA QUE EXISTE UN PRODUCTOR QUE POSEE UN PODER EN EL MERCADO Y ES UNICO EN LA INDUSTRIA DE PRODUCCION

¿QUE SON LOS BANCOS FEDERALES? SON LOS QUE AMINISTRAN LAS RESERVAS FEDERALES DE TODOS LOS GOBIERNOS SON AQUELLAS QUE POSEEN EL MONOPOLIO DE IMPRIMIR Y DISTRIBUIR DINERO
PARA QUE ALGO SE CONVIERTA EN UN MONOPOLIO ES NECESARIO QUE EN EL MERCADO NO EXISTAN PRODUCTOS O SERVICIOS QUE LO REMPLACEN Y POR LO TANTO ES LA UNICA POSIBILIDAD QUE
TIENE EL CONSUMIDOR DE COMPRARLO.
-LOS BANCOS FEDERALES SON LOS QUE ESTABLECEN LA PLITICA MONETARIA DE CADA PAIS (ESTABLECEN LAS REGLAS DEL JUEGO)
-ESTABLECEN LAS TASAS DE INTERES (ESTO PUEDE CONYEVAR A INFLACION O BIEN A AUMENTAR EL PODER ADQUISITIVO DE LAS PERSONAS)
-LA FED (RESERVA FEDERAL DE EEU), DESDE LA SEGUNDA GUERRA MUNDIAL, LA POLITICA MONETARIA QUE RIGE EN TODO EL MUNDO ES LA QUE ESTABLECIO ESTADOS UNIDOS
-LAS TASAS DE INTERES BAJAS SE ESTABLECEN GENERALEMENTE CON LA FINALIDAD DE AYUDAR A UN PAIS A QUE TENGA MAYOR PODER ADQUISITIVO CUANDO HAY COMPLICACIONES EN EL MERCADO
- LA SUBIDA DE TASA DE INTERES ES CON EL FIN DE QUE LOS BANCOS GANEN MAS Y PRODUCE INFLACION (SUBIDA DE PRECIOS)

DEVALUACION: ES RELATIVO YA QUE ES UNA COMPARACION DE DEVALUACION DE UNA MONEDA CON OTRA DIVISA QUE GENERALEMNTE ES EL DOLAR ESTADOUNIDENSE

TIPOS DE INVERSIONES:

INVERSION DE RENTA FIJA: DESDE QUE SE INVIERTE SE ESTABLECE INICIALMENTE LA CANTIDAD A PAGAR
-BONOS FEDERALES: SON INSTRUMENTOS A PARTIR DE LOS CUALES LOS GOBIERNOS LES PIDEN DINERO A LAS EMPRESAS Y PERSONAS (SEGUROS PERO BAJO RENDIMIENTO)

-INVERSION DE RENTA VARIABLE: NO SE SABE SI SE GANA O SE PIERDE NI EN QUE CANTIDAD (BOLSA DE VALORES, FONDOS INDEXADOS, ETF'S, FONODS DE INVERSION DE RENTA VARIABLE)
SE PUEDE PEREDER TODO PERO A LA VES SE PUEDE GANAR MUCHO.

INSTRUMENTOS INDEXADOS:
SE PUEDE INVERTIR EN EL SP500 QUE ES EN REALDAD INVERTIR INDIRECTAMENTE EN LAS 500 EMPRESAS DE ESTADOS UNIDOS MAS IMPORTANTES A NIVEL MUNDIAL
SP500 (STANDAR AND PUSH 500): ES UN INDICE (REFLEJA LAS UTILIDADES O PERDIDAS DE LAS EMPRESAS) QUE DISPERSA EL BENEFICIO GANADO ENTRE LAS 500 EMPRESAS

REGLA DE ORO EN INVERSION:
--CUANDO LAS TASAS DE INTERES BAJAN LA BOLSA DE VALORES SUBE Y VICEVERSA
--CUANDO SUBEN LAS ACCIONES BAJAN LOS BONOS FEDERALES
--CUANDO BAJAN LAS TASAS DE INTERES SUBEN LAS BOLSAS DE VALORES Y LA GRAN MAYORIA DE LOS INSTRUMENTO DE RENTAS VARIABLE
--CUANDO SUBEN LAS TASAS DE INTERES BAJAN LAS ACCIONES Y ACTIVOS DE RENTA VARIABLE

TIP:

SUBIDA DE TAZA DE INTERES --> TENEMOS MENOS DINERO --> NO QUEREMOS RIESGO (PROTEJEMOS) --> INVERTIMOS EN BONOS FEDERALES

INSTRUMENTOS DE INVERSION:

-FONDOS DE INVERSION INDEXADOS:A TRAVES DE ETF´s INDEXADO (REFLEJA EL COMPORTAMIENTO DEL INDICE)  A SP500
EN LOS ETF´S PAGAS COMISION Y LOS COSTOS DE MANTENIMIENTO SON BAJOS PORQUE NO HAY GESTORES QUE TRABAJEN ALTOS RENDIMIENTOS
LOS FONDOS INDEXADOS TE PERMITEN DIFERIR TUS IMPUESTOS (SE PUEDE REINVERTIR CONSTANTEMENTE Y DE ESA FORMA POR LEY EVADIR IMPUESTOS)

BOLSA DE VALORES

-CUANDO SE INVIERTE EN BOLSA DE VALORES ES EN REALIDAD COMO HACER UNA APUESTA SOBRE QUE LA EMPRESA GANARA A SUS COMPETIDORES
-CASAS DE BOLSA (BROKER): INTERMEDIARIOS ENTRE QUIEN VENDE ACCIONES Y QUIENES COMPRAN.
-FLUCTUACIONES DE PRECIOS DE ACCIONES
-SE PUEDE INVERTIR EN MATERIAS PRIMAS (ORO, PLATA) Y DIVISAS (MONEDAS DE INTERCAMBIO)
-BITCOIN NO ES UNA DIVISA PORQUE NO HA LOGRADO CONSOLIDARSE COMO TAL
-TODA DIVISA VA A TENDER A SU VALOR REAL ($0)


INVERSION ES AQUELLA DONDE SE SOSTIENE LA POSICION DURANTE UN PERIODO (INVERSION PASIVA --> NO REQUIERE DE TRABAJO)
TRADING ES UNA INVERSION ACTIVA PORQUE REQUIERE DE TRABAJO Y CONOCIMIENTO Y GESTION EMOCIONAL (ES COMERCIALIZAR)

FENOMENOS A CONCIDERAR:

-MERCADO BAJISTA: CUANDO LA CAIDA O PERDIDA DE VALOR SE DA DE MANERA SOSTENIDA Y PROLONGADA

-CORRECCION ECONOMICA: ES EN LA QUE EN UN MERCADO ALSISTA LOS PRECIOS PUEDEN BAJAR PARA CORREJIR SU VALOR

RECOMENDACIONES:
1. CONOCER LA EMPRESA EN LA QUE SE INVIERTE.
2. NO INVERTIR EN TRADING (NO FUNCIONA: IMPUESTOS, SE PIERDE A NO SER QUE SEAS EXPERTO Y GANES A COSTA DE OTROS)
3. PARA REALMENTE TENER GANANCIAS EN ACCIONES SE DEBE TENER UN TIEMPO DE ESPERA MINIMO DE 5 AÑOS Y PUEDE SER QUE HASTA 10 AÑOS
4. SI TE GUSTA CONSERVAR EL DINERO, NO INVIERTAS YA QUE HAY VOLATILIDAD (SON RIESGOSAS), HAY PEREDIDAS DEL 50%
5. LA BOLSA CAÉ EN PROMEDIO UNA VES CADA 15 AÑOS MAS DEL 30% (EXISTEN FORMAS DE DISMINUIR EL RIESGO: DIVERSIFICACION)
7. NO INVERTIR SI NO SE TIENEN CONOCIMIENTO (BUSCAR ASESORIA O ESTUDIAR PREVIAMENTE):
-¿QUE SE ESTA COMPRANDO?
-¿QUE ES UN DIVIDENDO?
-RENTA FIJA Y VARIABLE
-ETF'S
-FONDOS INDEXADOS
-RESERVAS FEDERALES
-TASAS DE INTERES
'''

'''
HABITOS FINANCIEROS

IDEA DE QUE VENDER ES DENIGRANTE
LA MAYORIA DE LOS HABITOS SON APRENDIDOS POR LA FAMILIA (PADRES) --> REEVALUAR COMPORTAMIENTO ANTE SITUACIONES ECONOMICAS
CONTENCION FINANCIERA: LIMITARSE A LO QUE SE TIENE SIN ADQUIRIR MAS
HABLAR DE DINERO ES DE MALA EDUCACION

RECOMENDACIONES:
PRESUPUESTO DE COMPRAS
COSTO DE VACACIONES (¿SE PUEDE?)
CUENTA PARA LOS NIÑOS EN BANCOS
'''

'''
¿EN DONDE INVERTIR?

-GBM
-BANGUAR
-BURSANET

¿EN QUE INVERTIR?
-INVERTIR EN REGAIAS
-INVERTIR EN ORO (SISTEMATICAMENTE--> NO ESPECULAR, COMPRAR CADA MES), TODOS LOS MERCADOS SE RECUPERAN
-INVERTIR EN CONOCIMIENTO
-INVERTIR EN NEGOCIO
-INVERTIR EN BIENES RAICES

EL DOLAR ES LA MONEDA GLOBAL

¿CUAL ES TU PERFIL DE INVERSIONISTA?

-ACTIVO (TRABAJANDO TODOS LOS DIAS EN SUS INVERSIONES VIENDO COMO CAMBIA LA BOLSA DE VALORES)
-PASIVO (COOCA SU INVERSION Y LA DEJA DURANTE AÑOS)

-BOLSA DE VALORES: INSTITUCION QUE SE ENCARGA DE VENDER LAS ACCIONES DE UNA EMPRESA QUE HA LOGRADO REUNIR TODOS LO REQUISITOS PARA CONVERTIRSE EN S.A.B. DE C.V.
-INTELIGENCIA EMOCIONAL (MIEDO--> VENDER, EUFORIA --> COMPRAR)
-MIENTRAS CONSERVES LA ACCION TEN POR SEGURO QUE SE VAN A RECUPERAR, SOLO QUE NO SE SABE EN CUANTO TIEMPO
-SABER EN QUE EMPRESA INVERTIR (ANALISIS FUNDAMENTAL Y TECNICO)
-ES MAS UTILIZADO EN EL ANALISIS FUNDAMENTAL (EVALUACION CUALITATIVA DE TRES ESTADOS FINANCIEROS)

1. ESTADO DE RESULTADOS
2. BALANCE GENERAL
3. ESTADO DE FLUJO DE EFECTIVO

-SON INFORMES DE 100 PAGINAS Y SI LAS LEES YA PUEDES CONOCER COMO DE BUENA ES UNA EMPRESA PUBLICA
-LAS EMPRESAS PUBLICAS DEJAN QUE LAS PERSONAS ACCEDAN A SUS ESTADOS FINANCIEROS
-LAS EMPRESAS MANEJAN TRES CONTABILIDADES (REAL, LA DE PROVEDORES,BANCOS E INVERSIONISTAS Y LA QUE LE MUESTRAN A ACIENDA)
-EL BETA ES UN PARA METRO IMPORTANTE YA QUE NOS DICE LA VOLATILIDA DE UNA EMPRESA (SUBIDAS Y BAJADAS ABRUPTAS --> INESTABLE)
-MIENTRAS MAS SOLIDA ES LA EMPRESA MENOS VOLATILIDAD
-EL VALOR DE LAS ACCIONES LAS DETERMINA EL MERCADO (QUIEN COMPRA Y VENDE)
-DIVIDENDOS: ADEMAS DEL PRECIO DE LA ACCION SE OFRECEN PAGOS TRIMESTRALES
-CONCENTRARSE EN ACCIONES Y CREIMIENTO DE LA EMPRESA
-APRENDER DE CURSOS Y LIBROS: EL INVERSOR INTELIGENTE, UN PASO POR DELANTE DE WALL STREET (PETTER LEANCH)
'''

'''
PARA GENEARLE A LOS BANCOS Y ESTADOS ES NECESARIO SUPERAR LA INFLACION:

-HACER INVERSIONES QUE SUPEREN LA INFLACION, ES DECIR QUE SI HACEMOS UNA INVERSION QUE TENGA RENDIMIENTOS DE 6% Y LA INFLACION ES DEL 8% ENTONCES SE ESTA POR DEBAJO
DE LA MIMA Y EN REALIDAD NO ESTAMOS TENINEDO UN GRAN PODER ADQUISITVO

-EN CADA CICLO HAY UN ACTIVO QUE GANA A LOS DEMAS (APOSTARLE A UN SOLO ACTIVO, NO DIVERSIFICAR)****************
-¿QUIEN DIJO QUE LA DIVERSIFICACION ESTA PARA LOS QUE NO SABEN?
'''

'''
LOS MEJORES ACTIVOS

MEXICO:

-BIENES INMUEBLES
-DIVISAS
-ACCIONES Y CRIPTOMONEDAS

EEU:

-DIVISAS
-INMUEBLES
-ACCIONES
-CRIPTOMONEDAS

MIENTRAS MAS RICOS SON LOS PAISES INVIERTEN MAYORMENTE EN INMUEBLES
COMPRAR Y VENDER PROPIEDADES (INVERTIR EN FIBRAS:RENTA FIJA Y VARIABLE)
ALQUILERES COMERCIALES
'''

'''
PRINCIPALES ACTIVOS DE REFUGIO

DEUDA PUBLICA: BONOS EMITIDOS POR LOS GOBIERNOS (TASA FIJA) --> CETES (9.66%) Y UDIBONOS (RECOMPENZA CON PORCENTAJE POR ENCIMA DE LA INFLACION12%)--> 3 AÑOS

DIVISAS: MONEDAS DE CURSO LEGAL DE LOS PAISES / NO RECOMENDADO SI NO GANAS EN LA MISMA MONEDA EN LA QUE INVIERTES (COBRO DE COMISION)
LAS 10 PINCIPALES SON:
-DINAR KUWAITI
-DINAR BARENTI
-RIAL OMANI

MATERIA PRIMA (DIVISA): ORO (PUREZA 99.99% Y 24 KILATES), ORO DE INVERSION (LINGOTES,MONEDAS Y MICROLINGOTES)--> 100 DOLARES (2000 MXN) ESTA EXENTO DE IVA
LA JOYERIA TRAE CONSIGO IVA


BOLSA DE VALORES CON INTERMEDIARIOS: FONDOS O ETF´s INDEXADOS (ACTIVOS PARA DISMINUIR RIESGO) --> SYP 500

INMUEBLES (TERRENOS URBANOS)
-SIEMPRE SUBEN DE PRECIO
-QUE CUENTEN CON TODOS LOS SERVICIOS
-CONOCER QUE VA A SUCEDER EN LAS CERCANIAS DEL TERRENO YA QUE ESTO AFECTARA SU PLUSVALIA
-CUIDADO CON LAS BURBUJAS INMOBILIARIAS (MUCHA GENTE ESTA COMPRANDO VARIAOS TERRENOS)
'''