'''
ANTES DE QUE PODAMOS OPTIMIZAR EL POTAFOLIO, NECESITAMOS APRENDER SOBRE BUCLES Y RANGOS.

UN BUCLE NOS PERMITE CORRER UNA PARTE DEL CODIGO REPETIDAS VECES.

CADA VES LA PARTE DEL CODIGO ES EJECUTADA, ESTO SE LLAMA UNA ITERACION.

POR EJEMPLO PODEMOS USAR UN BUCLE FOR PARA ITERAR SOBRE UN ARREGLO Y CALCULAR EL PRODUCTO DE SUS ELEMENTOS:
'''

precios = [3,5,2,8]

prod = 1

for p in precios:
    prod = prod*p

print(prod)

'''
APRENDIMOS COMO CALCULAR LA MEDIA PARA ANALIZAR Y EVALUAR UN PORTAFOLIO DE ACCIONES. AHORA PODEMOS USAR PYTHON PARA OPTIMIZAR EL PORTAFOLIO.

LA OPTIMIZACION DE UN PORTAFOLIO ES UNA TECNICA DE ASIGNACION DE ACTIVOS TAL QUE TENGAN EL MAXIMO RETORNO Y MINIMO DE RIESGO.

ESTO SE PUEDE HACER ENCONTRANDO LA ASIGNACION QUE RESULTA EN EL MAXIMO (sharpe ratio)

LA FORMA SIMPLE DE ENCONTRAR LA MEJOR ASIGNACION ES REVISAR VARIAS ASIGNACIONES ALEATORIAS Y ENCONTRAR EL QUE TIENE EL MEJOR Sharpe ratio

ESTE PROCESO DE ADIVINADO AL AZAR ES CONOCIDO COMO UNA SIMULACION MONTECARLO
'''

