'''
IDEAS PARA PROYECTOS:

1. APLICACION PARA RESTAURANT

2. DIRECTORIO DE EMPRESA CON SUBCARPETAS/GERENCIA/VENTAS

3. SISTEMA DE ADMINISTRACION DE BIBLIOTECA CON PRESTAMO DE LIBROS (UN LIBRO PRESTADO DEBERA MOVERSE DE CARPETA HACIA PRESTADOS)

4.CREAR JUEGO DE PIEDRA PAPEL O TIJERA
'''