'''
EN ESTE MODULO APRENDEREMOS COMO ACCEDER A DATOS FINANCIEROS DESDE LA WEB

VEREMOS DOS METODOS PARA ACCEDER A DATOS:

-WEB SCRAPING
-USANDO LIBRERIAS DE PYTHON

WEB SCRAPING: ES EL PROCESO DE USAR UN PROGRAMA PARA EXTRAER CONTENIDO Y DATOS PARA UN SITIO WEB.
EXTRAE EL CODIGO HTML SUBYACENTE DE UN SITIO WEB
ESTE METODO PUEDE SER UTILIZADO PARA EXTRAER DE CUALQUIER SITIO WEB PUBLICO.

LAS PAGINAS WEB PUEDEN TENER RESTRICCIONES SOBRE COMO PUEDES USAR SUS DATOS, ASI QUE ASEGURATE DE LEER SUS POLITICAS DE PRIOVACIDAD SI INTENTAS USAR SUS DATOS


OTRA FORMA DE ACCEDER A DATOS ES USANDO PAQUETERIAS DE PYTHON ESPECIALES.

UN EJEMPLO ES yfinance, EL CUAL OFRECE UNA FORMA CONVENIENTE PARA ACCEDER A DATOS DE YAHOO FINANCE.

EN LAS SIGUIENTES LECCIONES APRENDEREMOS COMO ACCEDER A DATOS DE YAHOO FINANCE USANDO SCRAPING.
'''