'''
31 DE DICIEMBRE

ESTAS TRABAJANDO CON EL ARCHIVO CSV 'ca-covid' QUE CONTIENE LOS DATOS DE INFECCION DE COVID-19 EN CALIFORNIA PARA EL AÑO 2020.
EL ARCHIVO PROPORCIONA DATOS SOBRE LOS CASOS DIARIOS Y LAS MUERTES DE TODOO EL AÑO.
ENCUENTRA Y GENERA LA FILA QUE CORRESPONDA AL 31 DE DICIEMBRE DEL 2020.

LA FECHA SOLICITADA ES LA ULTIMA FILA DEL CONJUNTO DE DATOS, POR LO QUE PUEDES UTILIZAR LA INDEXACION PARA SELECCIONARLA.
'''
import pandas as pd

df = pd.read_csv('ca-covid.csv')

df.set.index('date',inplace=True)
df.dorp('state',axis = 1, inplace=True)

#LO UNCIO QUE SE AGREGO FUE ESTO:
print(df.iloc[-1])