'''
INDEXACION

PODEMOS SELECCIONAR UNA SOLA COLUMNA ESPECIFICANDO SU NOMBRE ENTRE CORCHETES:

print(df["ages"])

EL RESULTADO ES UN OBJETO SERIES.

SI QUEREMOS SELECCIONAR VARIAS COLUMNAS, PODEMOS ESPECIFICAR UNA LISTA DE NOMBRES DE COLUMNAS

print(df["ages", "heights"])

ESTA VES EL RESULTADO ES UN DATAFRAME, YA QUE INCLUYE VARIAS COLUMNAS.

ESTO ES UTIL CUANDO NECESITAMOS SELECCIONAR SOLO UNA PARTE DE LAS COLUMNAS DE DATOS.

SEGMENTACION

PANDAS USA LA FUNCION ILOC PARA SELECCIONAR DATOS BASADOS EN SU CODIGO NUMERICO.

FUNCIONA DE LA MISMA MANERA QUE LA INDEXACION DE LISTAS EN PYTHON.

#EJEMPLO:

#third row

print(df.iloc[2])

#first 3 rows

print(df.iloc[:3])

#rows 2 to 3 columns

print(df.iloc[1:3])

iloc SIGUE LAS MISMAS REGLAS QUE LA SEGMENTACION DE LISTA EN PYTHON.

CONDICIONES

TAMBIEN PODEMOS SELECCIONAR LOS DATOS EN FUNCION DE UNA CONDICION.

POR EJEMPLO SELECCIONAMOS TODAS LAS FILAS EN LAS QUE AGE ES MAYOR QUE 18 Y HEIGHT ES SUPERIOR A 180.

df[(df["ages"]>18)] & (df["ages"]>180)
'''



