'''
PANDAS ES UNA LIBRERIA DE LAS MAS POPULARES EN CIENCIA DE DATOS DE PYTHON. FACIL DE USAR, ESTA CONSTRUIDA SOBRE NUMPY Y COMPARTE MUCHAS FUNCIONES Y PROPIUEDADES.

CON PANDAS, PUEDES LEER Y EXTRAER DATOS DE ARCHIVOS, TRANSFORMARLOS Y ANALIZARLOS, CALCULAR ESTADISTICAS Y CORRELACIONES, ETC.

PARA UTILIZAR PANDAS ES NECESARIO IMPORTARLO PRIMERO Y GENERALMENTE SE UTILIZA pd PERO PUEDE USARSE OTRO NOMBRE CORTO PARA LLAMARLA.

PANDAS SEE DERIVA DEL TERMINO "PANEL DATA (DATOS DE PANEL)", UN TERMINO ECONOMETRICO PARA LOS CONJUNTOS DE DATOS QUE INCLUYEN OBSERVACIONES A LO LARGO DE MULTIPLES
PERIODOS DE TIEMPO PARA LOS MISMOS INDIVIDUOS.
'''
import pandas as pd

'''
SERIES Y MARCOS DE DATOS

LOS DOS COMPONENTES PRINCIPALES DE PANDAS SON LAS SERIES Y LOS DATAFRAME.

SERIES ES ESENCIALEMNTE UNA COLUMNA, Y UN DATAFRAME ES UNA TABLA MULTIDIMENCUIONAL FORMADA POR UNA COLECCION DE SERIES.

POR EJEMPLO ESL SIGUIENTE DATA FRAME SE COMPONE DE DOS SERIES (AGES Y HEIGHTS):

AGES     HEIGHTS
14         165
18         180
24         176
42         184

SE PUEDE PENSAR EN UNA SERIES COMO UNA MATRIZ UNIDIMENCIONAL, MIENTRAS QUE UN DATAFRAME ES UNA MATRIZ MULTIDIMENCIONAL.
'''